name: bot automation

on:
  pull_request:
    types:
      - opened

jobs:
  bot-automation:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' }}
    steps:
      - run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
