name: Format

on:
  push:
    branches:
      - main
    paths:
      - '**.swift'

jobs:
  swift-format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make format
      
      - name: Check Git Status
        id: git-status
        run: echo "has_changes=$(git status --porcelain)" >> $GITHUB_OUTPUT
      
      - uses: peter-evans/create-pull-request@v5
        if: steps.git-status.outputs.has_changes == 'true'
        with:
          delete-branch: true
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch-suffix: short-commit-hash
          commit-message: Run swift-format
          title: Run swift-format
